services:
  mysql:
    image: mysql:5.7
    container_name: mysql_dev
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webserver
    networks:
      - webserver
    volumes:
      - /home/hencejacki/docker-datas/mysql57:/var/lib/mysql
  
networks:
  webserver: {}